<?php

require_once __DIR__ . '/../vendor/autoload.php';

\Blade\Database\Sql\SqlBuilder::setEscapeMethod(function($value){
    return str_replace("'", "''", $value);
});

defined('TESTS_BLADE_DB_POSTGRES_ENABLED') || define('TESTS_BLADE_DB_POSTGRES_ENABLED', getenv('TESTS_BLADE_DB_POSTGRES_ENABLED'));
defined('TESTS_BLADE_DB_POSTGRES_HOST') || define('TESTS_BLADE_DB_POSTGRES_HOST', getenv('TESTS_BLADE_DB_POSTGRES_HOST'));
defined('TESTS_BLADE_DB_POSTGRES_USERNAME') || define('TESTS_BLADE_DB_POSTGRES_USERNAME', getenv('TESTS_BLADE_DB_POSTGRES_USERNAME'));
defined('TESTS_BLADE_DB_POSTGRES_PASSWORD') || define('TESTS_BLADE_DB_POSTGRES_PASSWORD', getenv('TESTS_BLADE_DB_POSTGRES_PASSWORD'));
defined('TESTS_BLADE_DB_POSTGRES_DATABASE') || define('TESTS_BLADE_DB_POSTGRES_DATABASE', getenv('TESTS_BLADE_DB_POSTGRES_DATABASE'));
defined('TESTS_BLADE_DB_POSTGRES_PORT') || define('TESTS_BLADE_DB_POSTGRES_PORT', getenv('TESTS_BLADE_DB_POSTGRES_PORT'));
